import { ProSkillBadge } from "@/components/card/experience";
import { Messages } from "global";

type ExperienceKey = keyof Messages["home"]["experiences"]["items"];

export const skillsByExperience = {
  singlespot1: [
    { name: "Python", type: "tech" },
    { name: "Rust", type: "tech" },
    { name: "Apache Pulsar", type: "tech" },
    { name: "Snowflake", type: "tech" },
    { name: "Docker", type: "tech" },
    { name: "AWS", type: "tech" },
    { name: "Kubernetes", type: "tech" },
    { name: "Microservices", type: "technical" },
    { name: "Data Engineering", type: "technical" },
    { name: "Cloud Architecture", type: "technical" },
    { name: "Technical Leadership", type: "soft" },
    { name: "Strategic Thinking", type: "soft" },
    { name: "Negotiation", type: "soft" },
  ],
  singlespot2: [
    { name: "Python", type: "tech" },
    { name: "Ruby on Rails", type: "tech" },
    { name: "PostgreSQL", type: "tech" },
    { name: "AWS", type: "tech" },
    { name: "Data Mining", type: "technical" },
    { name: "Machine Learning", type: "technical" },
    { name: "Data Engineering", type: "technical" },
    { name: "Backend Development", type: "technical" },
    { name: "Audience Segmentation", type: "technical" },
    { name: "Research", type: "technical" },
    { name: "Leadership", type: "soft" },
    { name: "Mentoring", type: "soft" },
  ],
  technicolor: [
    { name: "C++", type: "tech" },
    { name: "Qt", type: "tech" },
    { name: "Meshlab", type: "tech" },
    { name: "3D Graphics", type: "technical" },
    { name: "3D Mathematics", type: "technical" },
    { name: "Cryptography", type: "technical" },
    { name: "Security", type: "technical" },
    { name: "Algorithm Implementation", type: "technical" },
    { name: "Research", type: "technical" },
    { name: "Problem-Solving", type: "technical" },
    { name: "Collaboration", type: "soft" },
    { name: "Technical Writing", type: "soft" },
  ],
  epitech: [
    { name: "C", type: "tech" },
    { name: "Computer Science", type: "technical" },
    { name: "Algorithms", type: "technical" },
    { name: "Unix/Linux Administration", type: "technical" },
    { name: "Cybersecurity", type: "technical" },
    { name: "Mentoring", type: "soft" },
    { name: "Teaching", type: "soft" },
    { name: "Communication", type: "soft" },
    { name: "Teamwork", type: "soft" },
  ],
  creawave: [
    { name: "Python", type: "tech" },
    { name: "Django", type: "tech" },
    { name: "Full-Stack Web Development", type: "technical" },
    { name: "UI/UX Design", type: "technical" },
    { name: "Autonomy", type: "soft" },
    { name: "Communication", type: "soft" },
    { name: "Self-Learning", type: "soft" },
    { name: "Project Management", type: "soft" },
  ],
} satisfies Record<ExperienceKey, ProSkillBadge[]>;
